FROM ubuntu:18.04

LABEL "app.name"="MOS Compute Python"

# General
RUN apt-get update && apt-get install -y git

# Python
RUN apt-get install -y python3-pip
RUN pip3 install --upgrade pip
RUN pip3 install numpy cython

# Python dependencies
ADD ./requirements.txt /requirements.txt
RUN pip3 install -r requirements.txt

# MOS compute files
ADD . /mos-compute

# Entrypoint
WORKDIR /mos-compute
ENTRYPOINT ["./workers/worker.py"]